#!/bin/bash
	
PIDFILE=/var/run/occi4java.pid

cd /usr/share/occi4java/
if [ "$1" == "--daemon" ]; then
    java -jar occi4java.http-0.2.1.jar > /dev/null 2> /dev/null < /dev/null &
    echo -n $! > $PIDFILE
else
    java -jar occi4java.http-0.2.1.jar
fi